//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Contacts = new HashSet<Contact>();
            this.CustomerAddresses = new HashSet<CustomerAddress>();
            this.Requests = new HashSet<Request>();
            this.UserInfoes = new HashSet<UserInfo>();
        }
    
        public int CustomerId { get; set; }
        public string CompanyName { get; set; }
        public string DisplayName { get; set; }
        public string PhoneNumber { get; set; }
        public string CurrentContractCode { get; set; }
        public bool IsActive { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
    }
}
