//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryPlan
    {
        public DeliveryPlan()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int DeliveryPlanId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public Nullable<System.Guid> AssignedDeliveryStaffId { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public int DeliveryPlanStatus { get; set; }
        public string Note { get; set; }
        public string DeliveryOrder { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
