//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemManagement
    {
        public int ItemID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public string ImageMime { get; set; }
        public byte[] ImageData { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
