//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Items = new HashSet<Item>();
            this.Cargoes = new HashSet<Cargo>();
            this.PriceCategories = new HashSet<PriceCategory>();
        }
    
        public int OrderId { get; set; }
        public int RequestId { get; set; }
        public int DeliveryOptionId { get; set; }
        public int OrderPaymentTypeId { get; set; }
        public Nullable<int> DeliveryPlanId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> CollectedDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverPhone { get; set; }
        public string ReceiverAddress { get; set; }
        public Nullable<int> ReceiverAddressWardId { get; set; }
        public int ReceiverAddressDistrictId { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> Fee { get; set; }
        public int AmountToBeCollectedFromReceiver { get; set; }
        public int OrderStatus { get; set; }
        public string Note { get; set; }
    
        public virtual DeliveryOption DeliveryOption { get; set; }
        public virtual DeliveryPlan DeliveryPlan { get; set; }
        public virtual District District { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual Request Request { get; set; }
        public virtual Ward Ward { get; set; }
        public virtual OrderPaymentType OrderPaymentType { get; set; }
        public virtual Order Order1 { get; set; }
        public virtual Order Order2 { get; set; }
        public virtual ICollection<Cargo> Cargoes { get; set; }
        public virtual ICollection<PriceCategory> PriceCategories { get; set; }
    }
}
