//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityProvince
    {
        public CityProvince()
        {
            this.Districts = new HashSet<District>();
        }
    
        public int CityProvinceId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual ICollection<District> Districts { get; set; }
    }
}
