//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryMenInPlan
    {
        public int DeliveryMenInPlanId { get; set; }
        public Nullable<int> DeliveryMenId { get; set; }
        public Nullable<int> PlanId { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<decimal> EstimateDistance { get; set; }
        public Nullable<decimal> EstimateTime { get; set; }
    
        public virtual DeliveryMan DeliveryMan { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
