//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiktakStaff
    {
        public TiktakStaff()
        {
            this.Plans = new HashSet<Plan>();
            this.PriceCategories = new HashSet<PriceCategory>();
        }
    
        public int StaffId { get; set; }
        public string StaffRole { get; set; }
    
        public virtual ICollection<Plan> Plans { get; set; }
        public virtual ICollection<PriceCategory> PriceCategories { get; set; }
    }
}
