//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionPlan
    {
        public CollectionPlan()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int CollectionPlanId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public Nullable<System.Guid> AssignedDeliveryStaffId { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public int CollectionPlanStatus { get; set; }
        public string Note { get; set; }
        public string CollectionOrder { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
    }
}
